/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaEnvios.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sistemaEnvios.dao.EnvioDAO;
import sistemaEnvios.model.Envio;
import sistemaEnvios.model.Pessoa;


/**
 *
 * @author mayara
 */
public class TelaEnvios extends javax.swing.JFrame {

    /**
     * Creates new form TelaEnvios
     */
    public TelaEnvios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lbCodigoEnvio = new javax.swing.JLabel();
        txtCodigoEnvio = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        lbEnviarObjeto = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lbTituloRemetente = new javax.swing.JLabel();
        txtCodigoRemetente = new javax.swing.JTextField();
        lbCodigoRemetente = new javax.swing.JLabel();
        lbNomeRemetente = new javax.swing.JLabel();
        txtNomeRemetente = new javax.swing.JTextField();
        lbTituloDestinatario = new javax.swing.JLabel();
        txtCodigoDestinatario = new javax.swing.JTextField();
        lbCodigoDestinatario = new javax.swing.JLabel();
        lbNomeDestinatario = new javax.swing.JLabel();
        txtNomeDestinatario = new javax.swing.JTextField();
        lbNomeDestinatario1 = new javax.swing.JLabel();
        txtNomeObjeto = new javax.swing.JTextField();
        lbTituloObjeto = new javax.swing.JLabel();
        txtCodigoObjeto = new javax.swing.JTextField();
        lbCodigoDestinatario1 = new javax.swing.JLabel();
        lbFrete = new javax.swing.JLabel();
        txtFrete = new javax.swing.JTextField();
        lbTipoObjeto = new javax.swing.JLabel();
        txtTipoObjeto = new javax.swing.JTextField();
        txtCidadeRemetente = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        txtBairroRemetente = new javax.swing.JTextField();
        lbNumeroRemetente = new javax.swing.JLabel();
        txtNumeroRemetente = new javax.swing.JTextField();
        lbEstadoRemetente = new javax.swing.JLabel();
        lbLogradouro = new javax.swing.JLabel();
        txtEstadoRemetente = new javax.swing.JTextField();
        txtLogradouroRemetente = new javax.swing.JTextField();
        lbCepRemetente = new javax.swing.JLabel();
        txtCepRemetente = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        txtCidadeDestinatario = new javax.swing.JTextField();
        lbBairroDestinatario = new javax.swing.JLabel();
        txtBairroDestinatario = new javax.swing.JTextField();
        lbNumeroDestinatario = new javax.swing.JLabel();
        txtEstadoDestinatario = new javax.swing.JTextField();
        lbEstadoDestinatario = new javax.swing.JLabel();
        lbLogradouro1 = new javax.swing.JLabel();
        txtNumeroDestarinario = new javax.swing.JTextField();
        txtLogradouroDestinatario = new javax.swing.JTextField();
        lbCepDestinatario = new javax.swing.JLabel();
        txtCepDestinatario = new javax.swing.JTextField();
        lbCidadeDestinatario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lbCodigoEnvio.setText("Código:*");

        txtCodigoEnvio.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoEnvio.setToolTipText("");

        btnAlterar.setText("Alterar");

        lbEnviarObjeto.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        lbEnviarObjeto.setText("Enviar Objeto");

        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbTituloRemetente.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloRemetente.setText("REMETENTE:");

        txtCodigoRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRemetenteActionPerformed(evt);
            }
        });

        lbCodigoRemetente.setText("Código:*");

        lbNomeRemetente.setText("Nome do remetente:*");

        lbTituloDestinatario.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloDestinatario.setText("DESTINATÁRIO:");

        lbCodigoDestinatario.setText("Código:*");

        lbNomeDestinatario.setText("Nome do destinatário:*");

        lbNomeDestinatario1.setText("Nome do objeto:*");

        lbTituloObjeto.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbTituloObjeto.setText("OBJETO:");

        lbCodigoDestinatario1.setText("Código:*");

        lbFrete.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lbFrete.setText("FRETE:");

        lbTipoObjeto.setText("Tipo:*");

        lbBairro.setText("Bairro:*");

        lbNumeroRemetente.setText("Nº:*");

        txtNumeroRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroRemetenteActionPerformed(evt);
            }
        });

        lbEstadoRemetente.setText("Estado:*");

        lbLogradouro.setText("Logradouro:*");

        txtEstadoRemetente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoRemetenteActionPerformed(evt);
            }
        });

        lbCepRemetente.setText("CEP:*");

        lbCidade.setText("Cidade:*");

        lbBairroDestinatario.setText("Bairro:*");

        lbNumeroDestinatario.setText("Nº:*");

        txtEstadoDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoDestinatarioActionPerformed(evt);
            }
        });

        lbEstadoDestinatario.setText("Estado:*");

        lbLogradouro1.setText("Logradouro:*");

        txtNumeroDestarinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDestarinarioActionPerformed(evt);
            }
        });

        lbCepDestinatario.setText("CEP:*");

        lbCidadeDestinatario.setText("Cidade:*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCidadeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbBairroDestinatario)
                            .addComponent(txtBairroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addComponent(lbTipoObjeto)
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogradouro1)
                            .addComponent(lbLogradouro)
                            .addComponent(lbTituloDestinatario)
                            .addComponent(lbCodigoDestinatario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbCepDestinatario)
                                        .addComponent(txtCepDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNomeDestinatario)
                                        .addComponent(txtNomeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbBairro))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbNumeroRemetente))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbEstadoRemetente)
                                                    .addComponent(txtEstadoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbCepRemetente)
                                                .addComponent(txtCepRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(lbTituloObjeto)
                            .addComponent(lbCidade)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbEnviarObjeto))
                            .addComponent(txtCodigoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigoEnvio)
                            .addComponent(txtCodigoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogradouroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogradouroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCodigoRemetente, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTituloRemetente, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lbCodigoRemetente))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeRemetente)
                                    .addComponent(txtNomeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtCidadeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFrete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFrete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbCodigoDestinatario1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNomeDestinatario1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNomeObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                                    .addComponent(txtCodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTipoObjeto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbCidadeDestinatario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtNumeroDestarinario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbNumeroDestinatario)
                                        .addGap(77, 77, 77)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEstadoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbEstadoDestinatario))))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbEnviarObjeto)
                .addGap(18, 18, 18)
                .addComponent(lbCodigoEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbTituloRemetente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoRemetente)
                    .addComponent(lbNomeRemetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeRemetente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro)
                    .addComponent(lbCepRemetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepRemetente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbNumeroRemetente)
                    .addComponent(lbEstadoRemetente)
                    .addComponent(lbBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidadeRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoRemetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(lbTituloDestinatario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoDestinatario)
                    .addComponent(lbNomeDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogradouro1)
                    .addComponent(lbCepDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidadeDestinatario)
                    .addComponent(lbNumeroDestinatario)
                    .addComponent(lbEstadoDestinatario)
                    .addComponent(lbBairroDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairroDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCidadeDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEstadoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroDestarinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(lbTituloObjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoDestinatario1)
                    .addComponent(lbNomeDestinatario1)
                    .addComponent(lbTipoObjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFrete)
                    .addComponent(txtFrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar)
                    .addComponent(btnAlterar)
                    .addComponent(btnSalvar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Envio envio = new Envio(
                txtCodigoEnvio.getText(),
                txtFrete.getText(),
                txtCodigoRemetente.getText(),
                txtCodigoDestinatario.getText(),
                txtCodigoObjeto.getText());
        EnvioDAO enviodao = new EnvioDAO();
        enviodao.salvarEnvio(envio);
        JOptionPane.showMessageDialog(null, "Objeto salvo com sucesso!");      
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodigoRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRemetenteActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtNumeroRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroRemetenteActionPerformed

    private void txtEstadoRemetenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoRemetenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoRemetenteActionPerformed

    private void txtEstadoDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoDestinatarioActionPerformed

    private void txtNumeroDestarinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDestarinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDestarinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEnvios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEnvios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBairroDestinatario;
    private javax.swing.JLabel lbCepDestinatario;
    private javax.swing.JLabel lbCepRemetente;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCidadeDestinatario;
    private javax.swing.JLabel lbCodigoDestinatario;
    private javax.swing.JLabel lbCodigoDestinatario1;
    private javax.swing.JLabel lbCodigoEnvio;
    private javax.swing.JLabel lbCodigoRemetente;
    private javax.swing.JLabel lbEnviarObjeto;
    private javax.swing.JLabel lbEstadoDestinatario;
    private javax.swing.JLabel lbEstadoRemetente;
    private javax.swing.JLabel lbFrete;
    private javax.swing.JLabel lbLogradouro;
    private javax.swing.JLabel lbLogradouro1;
    private javax.swing.JLabel lbNomeDestinatario;
    private javax.swing.JLabel lbNomeDestinatario1;
    private javax.swing.JLabel lbNomeRemetente;
    private javax.swing.JLabel lbNumeroDestinatario;
    private javax.swing.JLabel lbNumeroRemetente;
    private javax.swing.JLabel lbTipoObjeto;
    private javax.swing.JLabel lbTituloDestinatario;
    private javax.swing.JLabel lbTituloObjeto;
    private javax.swing.JLabel lbTituloRemetente;
    private javax.swing.JTextField txtBairroDestinatario;
    private javax.swing.JTextField txtBairroRemetente;
    private javax.swing.JTextField txtCepDestinatario;
    private javax.swing.JTextField txtCepRemetente;
    private javax.swing.JTextField txtCidadeDestinatario;
    private javax.swing.JTextField txtCidadeRemetente;
    private javax.swing.JTextField txtCodigoDestinatario;
    private javax.swing.JTextField txtCodigoEnvio;
    private javax.swing.JTextField txtCodigoObjeto;
    private javax.swing.JTextField txtCodigoRemetente;
    private javax.swing.JTextField txtEstadoDestinatario;
    private javax.swing.JTextField txtEstadoRemetente;
    private javax.swing.JTextField txtFrete;
    private javax.swing.JTextField txtLogradouroDestinatario;
    private javax.swing.JTextField txtLogradouroRemetente;
    private javax.swing.JTextField txtNomeDestinatario;
    private javax.swing.JTextField txtNomeObjeto;
    private javax.swing.JTextField txtNomeRemetente;
    private javax.swing.JTextField txtNumeroDestarinario;
    private javax.swing.JTextField txtNumeroRemetente;
    private javax.swing.JTextField txtTipoObjeto;
    // End of variables declaration//GEN-END:variables
}
